### ISSUE TITLE
Playblast/Render All not generating a complete sequence video (mp4) on MacOs (Silicon)

### ISSUE THREAD

**Issue by piotrnikov** [ubisoft/shotmanager#46]
**Infos on the context**
- Add-on version: V2-0-225
- Blender version, from installer or from zip: 3.4 Alpha
- Blender was launched in Admin mode? Yes
- OS: 12.6 (Apple Silicon)
- Bug was also on previous versions (I don't know / No / Yes, seen on version x.x): Don't know. Works as intended on Win10-11

**Describe the bug**
Click on Render All/  Playblast doesn't result in a complete readable mp4

**To Reproduce**
1. Click on Render all or Playbast
2. Check destination folder.
3. Separate mp4 shot files are there but no global one. It seems like the "gluing" of those files together hasn't happened.

<img width="228" alt="Screenshot 2022-09-20 at 12 40 37" src="https://user-images.githubusercontent.com/28474540/191238087-8b9f7a20-ce15-4283-a572-ce03e3d0aa37.png">
The generated .mp4 file is just 11Ko, so it's basically empty (and doesn't play of course).

**Expected behavior**
A playable global mp4 of the complete sequence

**Additional context**
In case it's useful, here is a scene that works on Win10 but not on Mac (you just need to point it to a proper Destination Folder):
[Playblast_Win10.blend.zip](https://github.com/ubisoft/shotmanager/files/9606721/Playblast_Win10.blend.zip)
Here is a scene that was created on Mac but that doesn't work on Win10:
[Playblast_MacOs.blend.zip](https://github.com/ubisoft/shotmanager/files/9606727/Playblast_MacOs.blend.zip)
And here is what the Terminal tells me when I try rendering out a Playblast:
[PlayBlast_Log.txt](https://github.com/ubisoft/shotmanager/files/9607244/PlayBlast_Log.txt)

Tell me if you need anything else to make this work.
And sorry for all my (Mac related it seems) issues :) 
Thanks!!!

Piotr

**Comment by werwack** [comment]
Hi @piotrnikov,
I do apologize for my late answer. Been quite busy.

The bug you mentioned can be either a regression of Shot Manager - I will check that - or an issue specific to the platform or the Blender version.

As you may know from the main page, Shot Manager is developed on Windows and I have no access nor real demand from our internal productions to other OS. So because we try to make the code as generic as possible it is supposed to work on other platforms too but... So the best we can do overcome that is to exchange, do some specific tests and see if there is something in the log.

**The other thing is that the version of Blender on which you faced the issue is not a supported one**. By that I mean it is interesting, for the sake of the development and robustness of the add-on, to try it from time to time on versions that are not released yet (beta), but final code cannot rely on that because there are still chances that something change between the beta and the release. And that is even more true for alpha versions, because quite often those versions are not complete (some package may not be included in the distribution) and the stability is certainly not there. All that to say I cannot really help for code running on alpha.

The current version of Blender is 3.3.1. Can you tell me if you have the issue on that version too?
Thank you for your understanding.

**Comment by piotrnikov** [comment]
Please don't apologize!!! The stuff you're doing is awesome and I (we!) can't thank you enough :)
Also I realize that not that many people use Macs (even less M1s) with Blender.
Anyways, I'm sorry to bug you with this.
I've just tried with 3.3.1 and it doesn't work either.
I've attached 2 log files in the hope it can help.
This one is when I launch Blender.
[Blender_Start_Log.txt](https://github.com/ubisoft/shotmanager/files/9722866/Blender_Start_Log.txt)
And this one is when I try to Playblast (or generate anykind of movie):
[Blender_Playblast_Log.txt](https://github.com/ubisoft/shotmanager/files/9722876/Blender_Playblast_Log.txt)
As I said in my previous report, A directory is created, movies per shots are properly generated, but the compiled movie does not work.
Please tell me if you need anything else to help you...
Thanks again for everything!

**Comment by piotrnikov** [comment]
Do you have any ideas as to why it's doing this? It almost feels like it's not finding the individual shots to concatenate them. But what do I know.
Also I tried to find a workaround to this (generating a playblast of the whole sequence) but haven't found one yet.
If you have any ideas I'd be super grateful :)

**Comment by werwack** [comment]
I have a look possibly tonight. Not the first bug submitted on Playblast rendering recently, have to check.
Beside I also wrote the script to create the markers but to give it to you I have to publish a version.

**Comment by werwack** [comment]
Ok, I found the issue in the Playblast. This should be fixed in the beta version that has just been publised: [v2.1.24_Beta](https://github.com/ubisoft/shotmanager/releases/tag/v2.1.24_Beta). Can you please check and confirm?

Thank you for all the provided materials. The scenes and the log helped a lot to debug - and to see how you are working! :D

According to what I understand from your context of use I would recommend you activate the Project Settings in your scenes. That would ensure you and your team are using the same configuration throughout files.
The Projects Settings panel is the second item in the Settings menu (the "wheel" icon at the top right of the Shot Manager panel). Once found its use should be pretty well understandable (hopefully, cause not documented at the moment :D )

**Comment by piotrnikov** [comment]
Thanks so much again for looking into this.
Sorry but it's still not working for me.
Here is a video of my process:
https://user-images.githubusercontent.com/28474540/195054359-88ecbe95-95a3-4c66-b232-04239b207bc0.mp4
The log file:
[Log.txt](https://github.com/ubisoft/shotmanager/files/9753676/Log.txt)
Doing the same thing on pc works as intended, so it feels like a macos problem (not sure if this occurs on Intel, but I don't think it's processor related).
Tell me if you need anything...

**Comment by werwack** [comment]
Oki, thanks a lot for the video. Will test it again this afternoon with your exact settings.

**Comment by werwack** [comment]
Hi @piotrnikov,
I believe I fixed the thing!
Can you try the latest published beta please?
[V 2.1.27 Beta](https://github.com/ubisoft/shotmanager/releases/tag/v2.1.27_Beta)

Basically I ensure in a better way that the file format for the Playblast and the shots rendering are better supported.
I also fixed the error you had when pressing on the button to open the renderings in a file browser. That was the only issue that was OS specific.

**Comment by piotrnikov** [comment]
Hello again @werwack :)
I just tried it. 
. The Open Folder now works.
. The rendering Playblast deleted all my files on my Desktop where I chose to save!!!!
Not my folders though. 
Also the resulting mp4 still doesn't work. Sorry...
Here is the video:

https://user-images.githubusercontent.com/28474540/195283384-4a186393-e2dc-4609-877e-0b361b90ece5.mp4

**Comment by werwack** [comment]
Arf... Sorry :/
I removed the beta version from downloadable packages.

Ok, a few things:

- The content of the Take folder where the files are rendered sees some content flushed when a rendering is done. Hence when a shot (or all shots according to the type of rendering that is asked for) is re-rendered (and unless the Re-Render Existing Shot Videos is UNchecked) the folder of that shot is deleted and recreated. This ensure the fact that the shot movie is using only the latest rendered images.
- There is no such thing as incremental rendering folders at the moment
- When doing a playblast the folders of the rendered shots are also flushed - Which, I see it only now, is quite dommageable and I should change asap.
- Other folders than the rendering ones should be left untouched - I will check here and thanks to your video why they are affected
- Hum, honestly, I doubt that renderind directly onto the OS desktop is a very good practice 🙄 I would deeply recommend to have a dedicated rendered folder not far from the Blender file itself. Especially when using a beta...

I come back to you asap

**Comment by piotrnikov** [comment]
It's ok :)
Thanks for al the clarification.
I know for the Desktop thing...  I like living dangerously I guess!
Just another small thing (maybe). I don't think the option open in player works... It should open Quicktime player I guess, but doesn't...

**Comment by werwack** [comment]
Hi Piotr,
I think I got it! Fingers crossed! (cause I fixed it blindly)
From what I saw it all comes from a problem of paths on Mac, due to a mix between / and \\ separators in paths. Thanks for the logs you provided before 😉

Can you please try this: https://we.tl/t-buqK6EzqVs
Ideally can you try in the same conditions as your last video? On the desktop I mean, and let me know what you loose this time 😅

I also did a change on the temp rendering folders. When using the playblast it will not screw up the rendering folders anymore.

Note that this version is still a beta. Appart from the paths and rendering issues you mentioned I noticed an error message when switching shots with drawing mode activated. Will fix it tomorrow. (well, this morning).

Btw, you may be interested by this upcoming presentation of Shot Manager by the storyboarder Spitfire: [BLENDER LIVESTREAM : 'UBISOFT SHOT MANAGER' ADDON DEMO](https://www.youtube.com/watch?v=8yBjm6ojwe8)

**Comment by werwack** [comment]
Also let me know if the player works now...

**Comment by piotrnikov** [comment]
Hi @werwack !!
Thanks again for this! It's still not working, but you're right the output images are not found so it's a huge step. Here is a partial log:
---- Importing image sequences ----
self.inputBGMediaPath: /Users/pyercoffin/Desktop/\Main_Take\Sh0000_IntermPlayblast\/./Sh0000_####.jpg
 *** Rendered shot not found: /Users/pyercoffin/Desktop/\Main_Take\Sh0000_IntermPlayblast\/./Sh0000_####.jpg
 *** Rendered shot not found: /Users/pyercoffin/Desktop/\Main_Take\Sh0000_IntermPlayblast\/./Act01_Seq0001_Sh0000.wav
atFrame: 0

The correct directory should read /Users/pyercoffin/Desktop/Main_Take/Sh0000_IntermPlayblast/Sh0000_####.jpg
So it's that weird portion before the name of the padded files (slash dot slash) that seems wrong...
If that is the problem, shouldn't it also be on Linux? Just asking for those working on Linux :)
Other than that, the files on my Desktop are no longer deleted so yipee!!
Tell me if you need a complete log or a video, but it seems your super close!!!
Tell me, and thank you again!

**Comment by werwack** [comment]
Ok, another try: [V2.1.29_Beta](https://we.tl/t-BxRa5EmrFC)
We should not be far...

Regarding the problem for people on Linux... Well, don't tell them! 🤣
(the fixes should work as well on Linux... I think)

Send again a log if thing is not working

**Comment by piotrnikov** [comment]
Hey again!
Still no go I'm afraid (on 3.3 LTS)...
https://user-images.githubusercontent.com/28474540/195970977-ec47612f-3760-41ce-b7ab-5b1c21a44953.mp4
[Log-3.3.txt](https://github.com/ubisoft/shotmanager/files/9791241/Log-3.3.txt)
It still doesn't look like it's finding the files.
Also for some reason it no longer installs on 3.4. 
It's an Alpha I know, I know :)
It's just so you know (it used to install fine)! Here is the error message in case you're curious.
[Log-3.4.txt](https://github.com/ubisoft/shotmanager/files/9791247/Log-3.4.txt)

**Comment by werwack** [comment]
Geeeeeeeeee!
Where is that coming from?
K, I double check... Again!
Thks for the report!

**Comment by werwack** [comment]
Question: Have you installed another 3.4b version since your previous test? Cause the log says "invalid bl_idname 'uas_shot_manager.convert_markers_from_camera_binding_to_shots', is too long, maximum length is 60" but this have not been changed recently.

**Comment by werwack** [comment]
Can you please try again with that one? https://we.tl/t-EROJRTr3kU
Send again the logs in case of troubles, I added some information in there.
Thanks again for your patience.

(In the meantime all that makes the PC version more robust 🤣)

**Comment by piotrnikov** [comment]
It works!!!!!!!!!! In 3.3 & 3.4.
Wow, what an adventure :)
Playblast, Open in Player, Open Explorer,... Everything!
(As a side note it'd be cool to choose you preferred player, RV, VLC,...)
Thanks so much for your patience in all of this!!!

**Comment by werwack** [comment]
Coooool!
Wonderful! I will add that to the next beta release.

Regarding the player: at the moment, and for each platform, the player that is called is the default one, the one associated with the media type at the OS level. It would be a considerable work to list all the players available on the OS of the user. I'm sure there are several other more relevant features you would prefer to see in SM instead (pick up one in batch shot renaming, projects settings improvements, material palettes in storyboard...). Feel free to share your needs and requests!
